### ISSUE TITLE
add TAG_SAVE_AS and CATEGORY_SAVE_AS to pelicanconf.py

### ISSUE THREAD

**Issue by Ninjani** [cryptogenomicon/angonaka#1]
A small correction that we added to the Astrochelys instructions more recently: to make the tag and category links  on an article page work you'll need to add the following to `pelicanconf.py`
```python
TAG_SAVE_AS = ''
CATEGORY_SAVE_AS = ''
```

Love the name!

**Comment by cryptogenomicon** [comment]
Great, thanks!
